# user: 
#export AWS_ACCESS_KEY_ID="AKIAIIBLADSL3U55R2QQ"
#export AWS_SECRET_ACCESS_KEY="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"

# user: terraform
export AWS_ACCESS_KEY_ID="AKIAUD4WZ43QCB567B7Y"
export AWS_SECRET_ACCESS_KEY="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"

#export AWS_DEFAULT_REGION="eu-central-1"
#export TF_VAR_server_port=8080
