---

- name: "lighttpd setup, 20230629"
#  hosts: localhost
  hosts: all
  become: yes

  vars:
    admin_user: "ubuntu"

  handlers:
  - name: restart_lighttpd
    ansible.builtin.service:
      name: lighttpd
      state: restarted

  tasks:
#  - name: "Upgrading all APT packages"
#    apt:
#      name: "*" 
#      state: latest
#      update_cache: yes 

  - name: "Allow new incoming SYN packets on TCP port 8080 (HTTP)"
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 8080
      jump: ACCEPT
      action: insert
      rule_num: 6

  - name: "Installing missing packages"
    ansible.builtin.apt:
      name:
        - lighttpd
      update_cache: yes 

  - name: "Setting custom home page"
    ansible.builtin.copy:
      src: "index.html"
      dest: "/var/www/html/index.html"

  - name: "Customizing lighttpd port"
    ansible.builtin.lineinfile:
      path: "/etc/lighttpd/lighttpd.conf"
      regexp: "^server.port"
      line: "server.port = 8080"
    notify:
      - restart_lighttpd

