---

- name: "Ubuntu setup, 20230413"
#  hosts: localhost
  hosts: all
  become: yes

  vars:
    admin_user: "ubuntu"

  tasks:
  - name: "Upgrading all APT packages"
    apt:
      name: "*" 
      state: latest
      update_cache: yes 

  - name: "Installing missing packages"
    ansible.builtin.apt:
      name:
#        - bind9-dnsutils
#        - vim

  - name: "Customizing history size and timestamp for {{ admin_user }}, 1/2"
    ansible.builtin.lineinfile:
      path: "/home/{{ admin_user }}/.bashrc"
      regexp: "^HISTSIZE=1000$"
      line: "HISTSIZE=10000"

  - name: "Customizing history size and timestamp for {{ admin_user }}, 2/2"
    ansible.builtin.replace:
      path: "/home/{{ admin_user }}/.bashrc"
      regexp: "^HISTFILESIZE=2000$"
      replace: 'HISTFILESIZE=20000\n\n# add timestamp to "history" output\nHISTTIMEFORMAT="%Y/%m/%d %T: "'

  - name: "Fixing locale settings in .bashrc"
    ansible.builtin.blockinfile:
      path: "/home/{{ admin_user }}/.bashrc"
      block: |
        export LANGUAGE="C.UTF-8"
        export LC_ALL="C.UTF-8"

  - name: "Customizing Bash aliases"
    ansible.builtin.copy:
      src: bash_aliases
      dest: "/home/{{ admin_user }}/.bash_aliases"
      owner: "{{ admin_user }}"
      group: "{{ admin_user }}"
      mode: "0644"
      backup: yes

