---

- name: "Ubuntu setup, 20230412"
  hosts: localhost
  become: yes

  tasks:
  - name: "Upgrading all APT packages"
    apt:
      name: "*" 
      state: latest
      update_cache: yes 

  - name: "Installing missing packages"
    ansible.builtin.apt:
      name:
#        - bind9-dnsutils
#        - vim

